language: python
python:
  - 3.4
  - 3.5
matrix:
  fast_finish: true
sudo: false
install:
  - "pip install -qU --compile pip"
  - "pip install -qU --compile behave coverage hypothesis nose pylint"
  - "pip install -qU --compile sphinx_rtd_theme"
script:
  - "pip install -qU --compile ."
  - "make commit"
  - "make docs"
